hide_download: true
hide_download_original: null
leftnav:
- identifier: 8ae57ecd-09c5-0062-e95b-c8611112aeee
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 2464daba-5eea-d895-5d0a-8cca0b7642d4
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 4a57ddf6-08bd-f0a3-6bee-3dc7af806ba8
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: e3a63dd0-2c7d-16d6-1b7c-f1431ef66db3
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 15f9834d-c5af-8fe3-f746-68c9a82ae6d0
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: 80f8f236-5c09-7550-7040-3328e6a08d0a
  name: Exams
  pageRef: /pages/exams
  weight: 60
- identifier: 460be76f-6b20-a5b8-80df-e04c87911356
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 70
